
export default {
    CATALOG_GET    : 'CATALOG_GET',
    CATALOG_DELETE : 'CATALOG_DELETE',
    PRODUCT_DELETE : 'PRODUCT_DELETE',
    PRODUCT_SAVE   : 'PRODUCT_SAVE',
    USER_SET       : 'USER_SET'
};
